// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUc1qp4jCuWX9jUx43lHBanTS9SZJ2AYE',
    appId: '1:387894768001:android:a930601d9e3fdd8bf27880',
    messagingSenderId: '387894768001',
    projectId: 'tstore-61da6',
    storageBucket: 'tstore-61da6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1KcqFr9Bczl3xIKW049bs2vc6Lj3p7k0',
    appId: '1:387894768001:ios:d3ea5946d7143f95f27880',
    messagingSenderId: '387894768001',
    projectId: 'tstore-61da6',
    storageBucket: 'tstore-61da6.appspot.com',
    androidClientId: '387894768001-68mef06joptaigq9784m7ek9i4er61qn.apps.googleusercontent.com',
    iosClientId: '387894768001-4iv9hiqga7h2s92d4t54vnoilbad796b.apps.googleusercontent.com',
    iosBundleId: 'com.example.cwtEcommerceApp',
  );
}
